name: marvel_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.17.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  pod_player: ^0.1.0
  webview_flutter: ^3.0.4
  flutter_app_icon_badge: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  get: ^4.6.1
  shared_preferences: ^2.0.8
  uuid: ^3.0.5
  intl: ^0.16.1
  intro_views_flutter: '^3.2.0'
  build_runner: ^2.2.0
  flutter_gen_runner:

flutter:
  uses-material-design: true
  assets:
    - assets/images/