import 'marvel.dart';

class MarvelConst {
  static const initialTodos = [
    Marvel.withId(
      id: 0,
      title: 'アイアンマン',
      image:
          'https://cv.bkmkn.kodansha.co.jp/9784062183062/9784062183062_w.jpg',
      startTime: '2008年',
      category: 'アイアンマン',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '0',
      webPage: 'https://youtu.be/EQN961LwSj8',
      page: 'https://movies.yahoo.co.jp/movie/330416/',
    ),
    Marvel.withId(
      id: 1,
      title: 'インクレディブル・ハルク',
      image:
          'https://review-kaitemita.com/wp-content/uploads/2020/04/ab0b285ae100cb3c0cef7af818216349.jpg',
      startTime: '2008年',
      category: 'ハルク',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '1',
      webPage: 'https://youtu.be/I6FHGBWqgYo',
      page: 'https://movies.yahoo.co.jp/movie/330415/',
    ),
    Marvel.withId(
      id: 2,
      title: 'アイアンマン２',
      image:
          'https://images-na.ssl-images-amazon.com/images/I/81TTSSamvhL._RI_.jpg',
      startTime: '2010年',
      category: 'アイアンマン',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '2',
      webPage: 'https://youtu.be/lPZejZaOXE0',
      page: 'https://movies.yahoo.co.jp/movie/335567/',
    ),
    Marvel.withId(
      id: 3,
      title: 'マイティ・ソー',
      image: 'https://m.media-amazon.com/images/I/712p0sJPAtL._AC_SY679_.jpg',
      startTime: '2011年',
      category: 'マイティ・ソー',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '3',
      webPage: 'https://youtu.be/zSIhvQFxOSM',
      page: 'https://movies.yahoo.co.jp/movie/338677/',
    ),
    Marvel.withId(
      id: 4,
      title: 'キャプテン・アメリカ\nザ・ファースト・アベンジャー',
      image:
          'https://marvel.disney.co.jp/content/dam/disney/images/studio/bd_ondemand/package/30000000006000_30000000006999/30000000006001.png',
      startTime: '2011年',
      category: 'キャプテン・アメリカ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '4',
      webPage: 'https://youtu.be/oVHa7YKEwYg',
      page: 'https://movies.yahoo.co.jp/movie/339722/',
    ),
    Marvel.withId(
      id: 5,
      title: 'アベンジャーズ',
      image:
          'https://marvel.disney.co.jp/content/dam/disney/images/studio/bd_ondemand/package/30000000006000_30000000006999/30000000006002.png',
      startTime: '2012年',
      category: 'アベンジャーズ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '5',
      webPage: 'https://youtu.be/GzGCh4mVZG4',
      page: 'https://movies.yahoo.co.jp/movie/341611/',
    ),
    Marvel.withId(
      id: 6,
      title: 'アイアンマン3',
      image: 'https://m.media-amazon.com/images/I/61Wfz2Zd2sL._AC_SY679_.jpg',
      startTime: '2013年',
      category: 'アイアンマン',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '6',
      webPage: 'https://youtu.be/XppWPnwQpGc',
      page: 'https://movies.yahoo.co.jp/movie/344443/',
    ),
    Marvel.withId(
      id: 7,
      title: 'マイティ・ソー\nダーク・ワールド',
      image: 'https://m.media-amazon.com/images/I/71z-0iFPXkL._AC_SY445_.jpg',
      startTime: '2014年',
      category: 'マイティ・ソー',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '7',
      webPage: 'https://youtu.be/Lw8Q6sgkErc',
      page: 'https://movies.yahoo.co.jp/movie/346662/',
    ),
    Marvel.withId(
      id: 8,
      title: 'キャプテン・アメリカ\nウィンター・ソルジャー',
      image:
          'https://images-na.ssl-images-amazon.com/images/I/91htnwkgYyL._RI_.jpg',
      startTime: '2014年',
      category: 'キャプテン・アメリカ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '8',
      webPage: 'https://youtu.be/3RhrsNUoz30',
      page: 'https://movies.yahoo.co.jp/movie/347842/',
    ),
    Marvel.withId(
      id: 9,
      title: 'ガーディアンズ・オブ・ギャラクシー',
      image:
          'https://images-na.ssl-images-amazon.com/images/I/A1rDcaxXz4L._RI_.jpg',
      startTime: '2014年',
      category: 'ガーディアンズ・オブ・ギャラクシー',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '9',
      webPage: 'https://youtu.be/jHPvHQCAxLY',
      page: 'https://movies.yahoo.co.jp/movie/349437/',
    ),
    Marvel.withId(
      id: 10,
      title: 'アベンジャーズ\nエイジ・オブ・ウルトロン',
      image:
          'https://marvel.disney.co.jp/content/dam/disney/images/studio/bd_ondemand/package/30000000006000_30000000006999/30000000006007.png',
      startTime: '2015年',
      category: 'アベンジャーズ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '10',
      webPage: 'https://youtu.be/ofHE2J8pWOo',
      page: 'https://movies.yahoo.co.jp/movie/352157/',
    ),
    Marvel.withId(
      id: 11,
      title: 'アントマン',
      image: 'https://m.media-amazon.com/images/I/71E9abm2ayL._AC_SY679_.jpg',
      startTime: '2015年',
      category: 'アントマン',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '11',
      webPage: 'https://youtu.be/DWc-8YryLfg',
      page: 'https://movies.yahoo.co.jp/movie/352769/',
    ),
    Marvel.withId(
        id: 12,
        title: 'シビル・ウォー\nキャプテン・アメリカ',
        image:
            'https://cdn-ak.f.st-hatena.com/images/fotolife/f/fuminnw/20181206/20181206020027.jpg',
        startTime: '2016年',
        category: 'キャプテン・アメリカ',
        isFavorite: false,
        isWatch: false,
        preferenceKey: '12',
        webPage: 'https://youtu.be/r4JrKFpREcE',
        page: 'https://movies.yahoo.co.jp/movie/355057/'),
    Marvel.withId(
      id: 13,
      title: 'ドクター・ストレンジ',
      image:
          'https://images-na.ssl-images-amazon.com/images/I/A1ETnS3mj6L._RI_.jpg',
      startTime: '2016年',
      category: 'ドクター・ストレンジ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '13',
      webPage: 'https://youtu.be/v6pAIzHglRU',
      page: 'https://movies.yahoo.co.jp/movie/357823/',
    ),
    Marvel.withId(
      id: 14,
      title: 'ガーディアンズ・オブ・ギャラクシー\nリミックス',
      image:
          'https://marvel.disney.co.jp/content/dam/disney/images/studio/bd_ondemand/package/30000000006000_30000000006999/30000000006011.png',
      startTime: '2017年',
      category: 'ガーディアンズ・オブ・ギャラクシー',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '14',
      webPage: 'https://youtu.be/rCi4r1j5kzc',
      page: 'https://movies.yahoo.co.jp/movie/359505/',
    ),
    Marvel.withId(
      id: 15,
      title: 'マイティ・ソー\nバトルロイヤル',
      image:
          'https://images-na.ssl-images-amazon.com/images/I/A1thgEKWwSL._RI_.jpg',
      startTime: '2017年',
      category: 'マイティ・ソー',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '15',
      webPage: 'https://youtu.be/7ZcBnbe1ma8',
      page: 'https://movies.yahoo.co.jp/movie/360620/',
    ),
    Marvel.withId(
      id: 16,
      title: 'スパイダーマン\nホームカミング',
      image:
          'https://img.mandarake.co.jp/webshopimg/03/00/933/0300740933/03007409333.jpg',
      startTime: '2017年',
      category: 'スパイダーマン',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '16',
      webPage: 'https://youtu.be/IO-wgJT6qNY',
      page: 'https://movies.yahoo.co.jp/movie/359026/',
    ),
    Marvel.withId(
      id: 17,
      title: 'ブラックパンサー',
      image:
          'http://fansvoice.jp/wp-content/uploads/2017/08/black-panther-ja-teaser-poster-724x1024.jpg',
      startTime: '2018年',
      category: 'ブラックパンサー',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '17',
      webPage: 'https://youtu.be/hjm9TvyPzxo',
      page: 'https://movies.yahoo.co.jp/movie/361665/',
    ),
    Marvel.withId(
      id: 18,
      title: 'アベンジャーズ\nインフィニティ・ウォー',
      image:
          'https://dtimes.jp/wp-content/uploads/2020/03/652b8632357a025b0df18cb6201eaf5b.jpg',
      startTime: '2018年',
      category: 'アベンジャーズ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '18',
      webPage: 'https://youtu.be/7rmUFAgsI4M',
      page: 'https://movies.yahoo.co.jp/movie/361806/',
    ),
    Marvel.withId(
      id: 19,
      title: 'アントマン＆ワスプ',
      image:
          'https://marvel.disney.co.jp/content/dam/marvel/movie/antman-wasp/story/story_antman-wasp_02.jpg',
      startTime: '2018年',
      category: 'アントマン＆ワスプ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '19',
      webPage: 'https://youtu.be/kvzIoVGjzes',
      page: 'https://movies.yahoo.co.jp/movie/364079/',
    ),
    Marvel.withId(
      id: 20,
      title: 'キャプテン・マーベル',
      image: 'https://m.media-amazon.com/images/I/71N4dSkqRoL._AC_SY445_.jpg',
      startTime: '2018年',
      category: 'キャプテン・マーベル',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '20',
      webPage: 'https://youtu.be/uiOzPr_1m0A',
      page: 'https://movies.yahoo.co.jp/movie/365988/',
    ),
    Marvel.withId(
      id: 21,
      title: 'アベンジャーズ\nエンドゲーム',
      image:
          'https://images-na.ssl-images-amazon.com/images/I/91Q0cUYL2-L._RI_.jpg',
      startTime: '2019年',
      category: 'アベンジャーズ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '21',
      webPage: 'https://youtu.be/S747rLiAeFE',
      page: 'https://movies.yahoo.co.jp/movie/366491/',
    ),
    Marvel.withId(
      id: 22,
      title: 'スパイダーマン\nファー・フロム・ホーム',
      image:
          'https://d2ueuvlup6lbue.cloudfront.net/attachments/315dda1903817909d2c73364d6449e565724f8bb/store/fitpad/300/420/313edf02c4751ec8706f6419437ed781e0b547ef5be2cacc13429f59881b/_.jpg',
      startTime: '2019年',
      category: 'スパイダーマン',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '22',
      webPage: 'https://youtu.be/JDE7Mlks1PU',
      page: 'https://movies.yahoo.co.jp/movie/366852/',
    ),
    Marvel.withId(
      id: 23,
      title: 'ワンダヴィジョン',
      image:
          'https://theriver.jp/wp-content/uploads/2020/09/31e87c9088381dcc67120796e5504963.jpg',
      startTime: '2019年',
      category: 'ワンダヴィジョン',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '23',
      webPage: 'https://youtu.be/tlGLlUBkczM',
      page: 'https://filmarks.com/dramas/7264/10454',
    ),
    Marvel.withId(
      id: 24,
      title: 'ロキ',
      image:
          'https://theriver.jp/wp-content/uploads/2021/06/7da40f4df4ee1222f3173fb3c862e3d6.jpg',
      startTime: '2021年',
      category: 'ロキ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '24',
      webPage: 'https://youtu.be/K1mU5FU-B3E',
      page: 'https://filmarks.com/dramas/7263/10451',
    ),
    Marvel.withId(
      id: 25,
      title: 'ブラック・ウィドウ',
      image:
          'https://marvel.disney.co.jp/content/dam/disney/images/studio/bd_ondemand/package/30000000006000_30000000006999/30000000006440.png',
      startTime: '2021年',
      category: 'ブラック・ウィドウ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '25',
      webPage: 'https://youtu.be/1-OKDBNaDUQ',
      page: 'https://movies.yahoo.co.jp/movie/370448/',
    ),
    Marvel.withId(
      id: 26,
      title: 'シャン・チー\nテン・リングスの伝説',
      image:
          'https://img.cinematoday.jp/a/-oGsbCZslZyW/_size_640x/_v_1629171854/1.jpg',
      startTime: '2021年',
      category: 'シャン・チー',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '26',
      webPage: 'https://youtu.be/qSF9Ih22o2k',
      page: 'https://movies.yahoo.co.jp/movie/376781/',
    ),
    Marvel.withId(
      id: 27,
      title: 'エターナルズ',
      image:
          'https://theriver.jp/wp-content/uploads/2021/05/7ff3e9c3eff069159b6073044accc4b6.jpg',
      startTime: '2021年',
      category: 'エターナルズ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '27',
      webPage: 'https://youtu.be/OIDbp-u7Qmo',
      page: 'https://movies.yahoo.co.jp/movie/376782/',
    ),
    Marvel.withId(
      id: 28,
      title: 'ホークアイ',
      image:
          'https://img2.animatetimes.com/2021/11/619d87f732813_ba85a3b7937f5263ef93d99af906302b.jpg',
      startTime: '2021年',
      category: 'ホークアイ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '28',
      webPage: 'https://youtu.be/fOPu94JZLr8',
      page: 'https://filmarks.com/dramas/7266/10455',
    ),
    Marvel.withId(
      id: 29,
      title: 'スパイダーマン\nノー・ウェイ・ホーム',
      image:
          'https://theriver.jp/wp-content/uploads/2022/08/SMRR_INTL_OnLine_1080x1350_TSR_01-1024x1280.jpg',
      startTime: '2019年',
      category: 'スパイダーマン',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '29',
      webPage: 'https://youtu.be/w86PoS0e0XI',
      page: 'https://movies.yahoo.co.jp/movie/378066/',
    ),
    Marvel.withId(
      id: 30,
      title: 'ムーンナイト',
      image:
          'https://img.cinematoday.jp/a/Y0sVKS4vG1eb/_size_640x/_v_1649252087/1.jpg',
      startTime: '2022年',
      category: 'ムーンナイト',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '30',
      webPage: 'https://youtu.be/grLPhTWYroY',
      page: 'https://filmarks.com/dramas/11499/15950',
    ),
    Marvel.withId(
      id: 31,
      title: 'ドクター・ストレンジ\nマルチバース・オブ・マッドネス',
      image:
          'https://realsound.jp/wp-content/uploads/2022/05/20220506-drstrange-02-331x468.jpeg',
      startTime: '2022年',
      category: 'ドクター・ストレンジ',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '31',
      webPage: 'https://youtu.be/Vx-5RMNJrko',
      page: 'https://movies.yahoo.co.jp/movie/380731/',
    ),
    Marvel.withId(
      id: 32,
      title: 'ミズ・マーベル',
      image:
          'https://img.cinematoday.jp/a/dMuBjrIZHVlR/_size_640x/_v_1654171917/main.jpg',
      startTime: '2022年',
      category: 'ミズ・マーベル',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '32',
      webPage: 'https://youtu.be/XfGxgXSmYT0',
      page: 'https://movies.yahoo.co.jp/movie/365988/',
    ),
    Marvel.withId(
      id: 33,
      title: 'ソー：ラブ＆サンダー',
      image:
          'https://marvel.disney.co.jp/content/disney/jp/marvel/movie/thor-love-and-thunder/news/20220524_01/_jcr_content/par/navi_vertical_child/navi_vertical_child_par/rss_article/mainImage2.img.jpg/1653374297983.jpg',
      startTime: '2022年',
      category: 'ソー',
      isFavorite: false,
      isWatch: false,
      preferenceKey: '33',
      webPage: 'https://youtu.be/pJ6-d_KwFqY',
      page: 'https://movies.yahoo.co.jp/movie/382432/',
    ),
  ];
}
